postprocessor:
  name: msp

model:
  num_classes: 10
  pretrained_weights: False
  freeze_weights: False

mlp:
  image_size: 224
  channels: 3
  patch_size: 16
  dim: 2048
  depth: 60
  expansion_factor: 10