trainer:
  lr: 1e-5
  optimizer: 'AdamW'
  lr_scheduler: 'ReduceLROnPlateau'

dataset:
  name: 'imagenet'
  batch_size: 4
  dataloader_num_workers: 8
  train:
    label_path: './VisAlign_dataset/train_split_filenames/final_train'
    imagenet21k_path: './VisAlign_dataset/train_files'
  eval:
    label_path: './VisAlign_dataset/train_split_filenames/final_eval'
    imagenet21k_path: './VisAlign_dataset/train_files'

model:
  num_classes: 10
  pretrained_weights: False
  freeze_weights: False

vit:
  embed_dim: 256
  hidden_dim: 512
  num_heads: 8
  num_layers: 6
  num_channels: 3
  patch_size: 4
  num_patches: 64
  dropout: 0.2

mlp:
  image_size: 224
  channels: 3
  patch_size: 16
  dim: 2048
  depth: 60
  expansion_factor: 10