trainer:
  lr: 1e-5
  optimizer: 'AdamW'
  lr_scheduler: 'ReduceLROnPlateau'

dataset:
  batch_size: 4
  dataloader_num_workers: 8
  train:
    label_path: '/home/edlab/jylee/RELIABLE/data/final_dataset/final_train'
    imagenet_path: '/home/data_storage/imagenet/train'
    celeba_path: '/home/data_storage/CelebA/celeba/img_align_celeba'
    giraffe_path: '/home/edlab/jylee/RELIABLE/data/animal/giraffe/data/train'
    kangaroo_path: '/home/edlab/jylee/RELIABLE/data/animal/kangaroo/data/train'
    lsp_path: '/home/edlab/jylee/RELIABLE/data/LSP/train'
  eval:
    label_path: '/home/edlab/jylee/RELIABLE/data/final_dataset/final_eval'
    imagenet_path: '/home/data_storage/imagenet/train'
    celeba_path: '/home/data_storage/CelebA/celeba/img_align_celeba'
    giraffe_path: '/home/edlab/jylee/RELIABLE/data/animal/giraffe/data/val'
    kangaroo_path: '/home/edlab/jylee/RELIABLE/data/animal/kangaroo/data/val'
    lsp_path: '/home/edlab/jylee/RELIABLE/data/LSP/train'

model:
  num_classes: 10
  pretrained_weights: False
  freeze_weights: False

vit:
  embed_dim: 256
  hidden_dim: 512
  num_heads: 8
  num_layers: 6
  num_channels: 3
  patch_size: 4
  num_patches: 64
  dropout: 0.2

mlp:
  image_size: 224
  channels: 3
  patch_size: 16
  dim: 2048
  depth: 60
  expansion_factor: 10